In [4]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
data=pd.read_csv('crimes.csv')
data

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA NAME,Crm Cd Desc,Vict Age,Vict Sex,Vict Descent,Weapon Desc,Status Desc,LOCATION
0,220314085,2022-07-22,2020-05-12,1110,Southwest,THEFT OF IDENTITY,27,F,B,NaN,Invest Cont,2500 S SYCAMORE AV
1,222013040,2022-08-06,2020-06-04,1620,Olympic,THEFT OF IDENTITY,60,M,H,NaN,Invest Cont,3300 SAN MARINO ST
2,220614831,2022-08-18,2020-08-17,1200,Hollywood,THEFT OF IDENTITY,28,M,H,NaN,Invest Cont,1900 TRANSIENT
3,231207725,2023-02-27,2020-01-27,635,77th Street,THEFT OF IDENTITY,37,M,H,NaN,Invest Cont,6200 4TH AV
4,220213256,2022-07-14,2020-07-14,900,Rampart,THEFT OF IDENTITY,79,M,B,NaN,Invest Cont,1200 W 7TH ST
...,...,...,...,...,...,...,...,...,...,...,...,...
185710,231510379,2023-05-29,2023-05-25,1100,N Hollywood,"BUNCO, GRAND THEFT",25,M,W,NaN,Invest Cont,5300 DENNY AV
185711,231604807,2023-01-27,2023-01-26,1800,Foothill,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",23,M,H,NaN,Invest Cont,12500 BRANFORD ST
185712,231606525,2023-03-22,2023-03-22,1000,Foothill,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",25,F,H,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,12800 FILMORE ST
185713,231210064,2023-04-12,2023-04-12,1630,77th Street,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",29,M,B,UNKNOWN WEAPON/OTHER WEAPON,Invest Cont,6100 S VERMONT AV
185714,230906458,2023-03-05,2023-03-05,900,Van Nuys,VANDALISM - MISDEAMEANOR ($399 OR UNDER),53,F,H,NaN,Invest Cont,14500 HARTLAND ST

In [6]:
'''Which hour has the highest frequency of crimes? Store as an integer variable called peak_crime_hour.'''
data['TIME OCC']= data['TIME OCC'].astype(str)
data['Hour'] = data['TIME OCC'].str[:2].astype(int)
peak_crime_hour = data['Hour'].value_counts().idxmax()
print(f"The hour with the highest frequency of crimes is: {peak_crime_hour}")

The hour with the highest frequency of crimes is: 12

In [7]:
'''Which area has the largest frequency of night crimes (crimes committed between 10pm and 3:59am)? Save as a string variable called peak_night_crime_location.'''
data['TIME OCC'] = data['TIME OCC'].astype(str)
data['Hour'] = data['TIME OCC'].str[:2].astype(int)
night_crimes = data[(data['Hour'] >= 22) | (data['Hour'] < 4)]
# Find the area with the largest frequency of night crimes
peak_night_crime_location = night_crimes['AREA NAME'].value_counts().idxmax()
# peak_night_crime_location=data['AREA NAME'].value_counts().idxmax()
peak_night_crime_location

'Central'

In [8]:
'''Identify the number of crimes committed against victims of different age groups. Save as a pandas Series called victim_ages, with age group labels "0-17", "18-25", "26-34", "35-44", "45-54", "55-64", and "65+" as the index and the frequency of crimes as the values.'''
# Define age bins and labels
bins = [0, 17, 25, 34, 44, 54, 64, 100]  # Assuming ages are capped at 100
labels = ["0-17", "18-25", "26-34", "35-44", "45-54", "55-64", "65+"]
data.dropna(subset=['Vict Age'],inplace=True)
data['Vict Age'] = pd.to_numeric(data['Vict Age'], errors='coerce')
data['Vict Age'] = pd.cut(data['Vict Age'], bins=bins, labels=labels, right=True)

# Count crimes in each age group
victim_ages = data['Vict Age'].value_counts().sort_index()
victim_ages

Vict Age
0-17      4528
18-25    28291
26-34    47470
35-44    42157
45-54    28353
55-64    20169
65+      14747
Name: count, dtype: int64